services:
  perplexica:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3050:3000'
    volumes:
      - data:/home/perplexica/data
      - uploads:/home/perplexica/uploads
    restart: unless-stopped

volumes:
  data:
    name: 'perplexica-data'
  uploads:
    name: 'perplexica-uploads'
